# Generated by Django 3.2 on 2023-02-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
