# Generated by Django 3.2 on 2023-04-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0012_character_defaultcharacter_defaultexit_defaultobject_defaultroom_object'),
        ('boards', '0004_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_boards', to='objects.Character'),
        ),
    ]
