# Generated by Django 3.2.12 on 2022-02-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Scene description'),
        ),
        migrations.AddField(
            model_name='scene',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Scene display name'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scene end time'),
        ),
        migrations.AlterField(
            model_name='scene',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Scene start time'),
        ),
    ]
