# Generated by Django 2.2.28 on 2023-02-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Minion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name of template for minion, defined in advance in the Minions database table')),
                ('lf', models.IntegerField(default=1000, verbose_name='LF')),
                ('maxlf', models.IntegerField(default=1000, verbose_name='Max LF')),
                ('ap', models.IntegerField(default=50, verbose_name='Starting AP')),
                ('maxap', models.IntegerField(default=100, verbose_name='Max AP')),
                ('ex', models.IntegerField(default=0, verbose_name='Starting EX')),
                ('maxex', models.IntegerField(default=100, verbose_name='Max EX')),
                ('power', models.IntegerField(default=125, verbose_name='Power')),
                ('knowledge', models.IntegerField(default=125, verbose_name='Knowledge')),
                ('parry', models.IntegerField(default=125, verbose_name='Parry')),
                ('barrier', models.IntegerField(default=125, verbose_name='Barrier')),
                ('speed', models.IntegerField(default=125, verbose_name='Speed')),
                ('arts', models.CharField(blank=True, default='', max_length=10000, verbose_name='Stringified list of Arts')),
            ],
        ),
    ]
