# Generated by Django 2.2.28 on 2023-03-15 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Default art name', verbose_name='Art name')),
                ('ap', models.IntegerField(blank=True, default=0, verbose_name='AP cost of art')),
                ('dmg', models.IntegerField(blank=True, default=0, verbose_name='Damage of art')),
                ('acc', models.IntegerField(blank=True, default=0, verbose_name='Accuracy of art')),
                ('stat', models.TextField(default='PWR', verbose_name='Main stat, either power (PWR) or knowledge (KNW)')),
                ('effects', models.TextField(blank=True, default='', verbose_name='Additional art effects')),
                ('isNormal', models.BooleanField(blank=True, default=False, verbose_name='States if this art is a normal')),
            ],
        ),
    ]
