# Generated by Django 2.2.28 on 2023-05-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0012_character_defaultcharacter_defaultexit_defaultobject_defaultroom_object'),
        ('arts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arts',
            name='character',
            field=models.ManyToManyField(to='objects.Character'),
        ),
    ]
