# Generated by Django 4.2.9 on 2026-02-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arts", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Arts",
            new_name="Art")
    ]
