# Generated by Django 4.2.9 on 2026-02-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("arts", "0002_art_rename_arts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="art",
            name="characters",
            field=models.ManyToManyField(related_name="art", to="objects.objectdb"),
        ),
    ]
