# Generated by Django 2.2.28 on 2023-05-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0012_character_defaultcharacter_defaultexit_defaultobject_defaultroom_object'),
        ('arts', '0002_arts_character'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arts',
            name='character',
        ),
        migrations.AddField(
            model_name='arts',
            name='characters',
            field=models.ManyToManyField(related_name='arts', to='objects.Character'),
        ),
    ]
