# Generated by Django 2.2.28 on 2023-06-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0004_auto_20230509_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arts',
            name='stat',
            field=models.TextField(default='Power', verbose_name='Main stat, either Power or Knowledge'),
        ),
    ]
