# Generated by Django 4.2.9 on 2025-10-24 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aspect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        default="Default aspect name", verbose_name="Aspect name"
                    ),
                ),
                (
                    "cost",
                    models.IntegerField(
                        blank=True, default=0, verbose_name="Capacity cost of Aspect"
                    ),
                ),
                (
                    "characters",
                    models.ManyToManyField(
                        related_name="aspects", to="objects.objectdb"
                    ),
                ),
                (
                    "linked_art",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aspects",
                        to="arts.arts",
                    ),
                ),
            ],
        ),
    ]
