# Generated by Django 4.2.9 on 2026-02-06 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("aspects", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="aspect",
            new_name="LinkedAspect"
        ),
        migrations.AlterField(
            model_name="linkedaspect",
            name="linked_art",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linkedaspect",
                to="arts.art",
            ),
        ),
    ]
